//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Vpdemo.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_VPDEMO_DIALOG               102
#define IDR_MAINFRAME                   128
#define IDR_MAIN_MENU                   129
#define IDD_TCPIPX                      130
#define IDD_NETBIOS                     131
#define IDD_TRAFFIC                     132
#define IDC_SESSIONLIST                 1001
#define IDC_PLAYERLIST                  1002
#define IDC_CREATESESSION               1003
#define IDC_PLAYERNAME                  1004
#define IDC_JOIN                        1005
#define IDC_TEXT                        1007
#define IDC_SENDMSG                     1008
#define IDC_EVENTLOG                    1009
#define IDC_STATICS                     1010
#define IDC_STATICP                     1011
#define IDC_RESCAN                      1012
#define IDC_MUSTDELIVER                 1013
#define IDC_BROADCAST                   1014
#define IDC_PORT                        1015
#define IDC_SERVER_ADDRESS              1016
#define IDC_STATION_NAME                1017
#define IDC_LANA                        1018
#define IDC_SENDBIG                     1019
#define IDC_LOADTEST                    1020
#define IDC_ACKDELAY                    1021
#define IDC_TICKDIVISOR                 1022
#define IDC_SENDSPERTICK                1023
#define IDC_SENDSPERBURST               1024
#define IDC_PACKETSIZE                  1025
#define IDC_NCBQUESIZE                  1027
#define IDC_COMWINSIZE                  1028
#define IDC_TCPIBUFSIZE                 1029
#define IDC_TCPOBUFSIZE                 1030
#define IDC_IPXIBUFSIZE                 1031
#define IDC_IPXOBUFSIZE                 1032
#define IDC_TCPFRAG                     1033
#define IDC_TICKFREQ                    1034
#define IDC_TCPFLOW                     1035
#define IDM_PROTOCOL_TCP                32771
#define IDM_PROTOCOL_IPX                32772
#define IDM_PROTOCOL_NETBIOS            32773
#define ID_PROTOCOL_COMM                32774
#define ID_PROTOCOL_MODEM               32775
#define ID_PROTOCOL_TAPI                32776
#define ID_PROTOCOL_DP                  32777
#define ID_PROTOCOL_ADVANCED            32778
#define ID_PROTOCOL_ADVANCED_CL         32778
#define ID_PROTOCOL_VPSTARTUP           32780
#define ID_PROTOCOL_VPENUMSES           32781
#define ID_PROTOCOL_ADVANCED_SRV        32782
#define ID_CFGSIM                       32783
#define IDM_GETSERVERADDR               32784

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         32785
#define _APS_NEXT_CONTROL_VALUE         1036
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
