//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by VPTST16.RC
//
#define IDR_MAINFRAME                   2
#define IDD_ABOUTBOX                    100
#define ID_VDMPLAY_GETVERSION           32771
#define ID_VDMPLAY_SUPPORTEDPROTOCOLS   32772
#define ID_VDMPLAY_STARTUP              32773
#define ID_VDMPLAY_CLEANUP              32774
#define ID_VDMPLAY_ENUMSESSIONS         32775
#define ID_VDMPLAY_CREATESESSION        32776
#define ID_VDMPLAY_JOINSESIONN          32777
#define ID_VDMPLAY_STOPENUMSESSIONS     32778
#define ID_TRANSPORTS_TCP               32779
#define ID_TRANSPORTS_IPX               32780
#define ID_TRANSPORTS_NETBIOS           32781
#define ID_VDMPLAY_CLOSESESSION         32783
#define ID_TRANSPORTS_COMM              32784
#define ID_TRANSPORTS_MODEM             32785
#define ID_VDMPLAY_ADVDLG               32786

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         32787
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
