/****************************************************************************
 *
 * (C) Unpublished Copyright of Novell, Inc.  All Rights Reserved.
 *
 * No part of this file may be duplicated, revised, translated, localized
 * or modified in any manner or compiled, linked or uploaded or downloaded
 * to or from any computer system without the prior written permission of
 * Novell, Inc.
 *
 ****************************************************************************/
#ifndef	_NWNET_HEADER_
#define	_NWNET_HEADER_

#ifndef __NWDSTYPE_H
#include <nwdstype.h>
#endif

#ifndef _NWALIAS_H
#include <nwalias.h>
#endif

#ifndef	__NWDSDEFS_H
#include <nwdsdefs.h>
#endif

#ifndef __NWDSERR_H
#include <nwdserr.h>
#endif

#ifndef	_NWDSNAME_HEADER_
#include <nwdsname.h>
#endif

#ifndef	_NWDSFILT_HEADER_
#include <nwdsfilt.h>
#endif

#ifndef	_NWDSDC_HEADER_
#include <nwdsdc.h>
#endif

#ifndef 	_NWDSMISC_HEADER_
#include <nwdsmisc.h>
#endif

#ifndef _NWDSACL_HEADER_
#include <nwdsacl.h>
#endif

#ifndef	_NWDSAUD_HEADER_
#include <nwdsaud.h>
#endif

#ifndef	_NWDSDSA_HEADER_
#include <nwdsdsa.h>
#endif

#ifndef	_NWDSSCH_HEADER_
#include <nwdssch.h>
#endif

#ifndef	_NWDSATTR_HEADER_
#include <nwdsattr.h>
#endif

#ifndef	_NWDSASA_HEADER_
#include <nwdsasa.h>
#endif

#ifndef	_NWDSPART_HEADER_
#include <nwdspart.h>
#endif

#ifndef _NWDSBUFT_HEADER_
#include <nwdsbuft.h>
#endif

#ifndef __NAMES_H
#include <nwdsnmtp.h>
#endif

#ifndef _UNICODE_HEADER_
#include <unicode.h>
#endif

#ifndef NWNLM
#ifndef _AUDIT_H
#include <nwaudit.h>
#endif

#ifndef NWNDSCON_INC
#include <nwndscon.h>
#endif

#else

#ifndef _NWNDS_H_INCLUDED
#include <nwnds.h>
#endif

#endif /* NWNLM */

#endif
