//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by VER16.RC
//
#define IDS_COMM_STAT_TITLE             1
#define IDS_COMM_STAT_INIT              2
#define IDS_COMM_STAT_DIAL              3
#define IDS_COMM_STAT_ERROR             4
#define IDS_COMM_STAT_BUSY              5
#define IDS_COMM_STAT_CONNECT           6
#define IDS_COMM_STAT_NO_ANSWER         7
#define IDS_COMM_STAT_NO_CONNECT        8
#define IDS_COMM_STAT_CONNECTED         9
#define IDS_COMM_STAT_WAITCALL          10
#define IDS_COMM_NOCARRIER              11
#define IDC_IP_SERVER_ADDR              1001
#define IDC_IP_SOCKET                   1002
#define IDC_IPX_NET_NUM                 1003
#define IDC_IPX_NODE_NUM                1004
#define IDC_IPX_SOCKET                  1005
#define IDC_NETBIOS_LANA                1006
#define IDC_DIRECT_PORT                 1007
#define IDC_MODEM_NUMBER                1009
#define IDC_MODEM_PORT                  1010
#define IDC_MODEM_ADV                   1011
#define IDC_CLIENT_INIT                 1013
#define IDC_NETBIOS_STATION             1014
#define IDC_DIAL_PREFIX                 1016
#define IDC_COMM_STATUS                 1016
#define IDC_DIAL_SUFFIX                 1017
#define IDC_COMM_DATA                   1017
#define IDC_CREATE_PHONE                1018
#define IDX_HELP                        1018
#define IDC_COMM_TRACE                  1019
#define IDC_CREATE_PORT                 1021
#define IDC_SERVER_INIT                 1021
#define IDC_CREATE_MDM_NAME             1022
#define IDC_CREATE_PNUM                 1023
#define IDC_PORT_BOX                    1142
#define IDC_PORT_PRMT                   1143
#define IDC_CREATE_NUM_PRMT             1149
#define IDD_ADV_TCPIP                   16101
#define IDD_ADV_MODEM_SETTINGS          16103
#define IDD_COMM_STAT                   16104
#define IDD_DIALOG2                     16105
#define IDI_ICON1                       16106
#define IDD_DIALOG1                     16192
#define IDD_ADV_IPX                     16193
#define IDD_ADV_NETBIOS                 16194
#define IDD_ADV_COMM                    16195
#define IDD_ADV_MODEM                   16196

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        16201
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1020
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
