//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Iserve.RC
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ISERVE_DIALOG               102
#define IDR_MAINFRAME                   128
#define IDR_MAIN_MENU                   129
#define IDD_SOCKET                      130
#define IDI_DISCON                      133
#define IDC_ServerList                  1000
#define IDC_START                       1001
#define IDC_EXIT                        1002
#define IDC_EDIT_NAME                   1003
#define IDC_EDIT_ADDR                   1004
#define IDC_EDIT_SOCKET                 1005
#define IDC_STOP                        32771
#define IDC_OPTIONS                     32773
#define IDC_HELP                        32774
#define IDC_ABOUT                       32775
#define IDS_NEW_SOCKET                  59142
#define IDS_TITLE                       59143
#define IDS_TITLE_WHEN_OFF              59144

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
