//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by VPTST.RC
//
#define IDD_ABOUTBOX                    101
#define IDR_MAINFRAME                   500
#define ID_VDMPLAY_VPSTARTUP            1000
#define ID_VDMPLAY_VPCLEANUP            1001
#define ID_VDMPLAY_VPGETVERSION         1002
#define ID_VDMPLAY_VPSUPPORTEDTRANSPORTS 1003
#define ID_VDMPLAY_VPSTARTENUMSESSIONS  1004
#define ID_VDMPLAY_VPSTOPENUMSESSION    1005
#define ID_TRANSPORT_TCP                2001
#define ID_TRANSPORT_NETBIOS            2002
#define ID_TRANSPORT_IPX                2003
#define ID_TRANSPORT_COMM               2004
#define ID_TRANSPORT_MODEM              2005
#define ID_TRANSPORT_TAPI               2006

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
