
all:	_amer _german
#all:	_amer _german _french _italian _spanish

_amer:
	cd 9
	nmake
	cd ..

_german:
	cd 7
	nmake
	cd ..

_french:
	cd 12
	nmake
	cd ..

_italian:
	cd 16
	nmake
	cd ..

_spanish:
	cd 10
	nmake
	cd ..
