.SUFFIXES : .raw .wav 

RAW = 	sys01.raw \
		sys02.raw \
		sys03.raw \
		sys04.raw \
		sys05.raw \
		sys06.raw \
		sys07.raw \
		sys08.raw \
		sys09.raw \
		sys10.raw \
		sys11.raw \
		sys12.raw \
		sys13.raw \
		sys14.raw \
		rct01.raw \
		com01.raw \
		com02.raw \
		com03.raw \
		com04.raw \
		com05.raw \
		com06.raw \
		com07.raw \
		com08.raw \
		com09.raw \
		com10.raw \
		com11.raw \
		com12.raw \
		com13.raw \
		com14.raw \
		com15.raw \
		com16.raw \
		com17.raw \
		com18.raw \
		com19.raw \
		com20.raw \
		bld01.raw \
		bld02.raw \
		bld03.raw \
		bld04.raw \
		bld05.raw \
		bld06.raw \
		sci01.raw \
		sci02.raw \
		sci03.raw \
		sci04.raw \
		rec01.raw \
		rec02.raw \
		rec03.raw \
		rec04.raw \
		tem01.raw \
		tem02.raw \
		tem03.raw \
		tem04.raw \
		tem05.raw \
		tem06.raw \
		tem07.raw \
		tem08.raw \
		tem09.raw \
		tem10.raw \
		tem11.raw \
		tem12.raw \
		tem13.raw \
		tem14.raw \
		tem15.raw \
		tem16.raw \
		tem17.raw \
		tem18.raw \
		fac01.raw \
		fac02.raw \
		fac03.raw \
		fac04.raw \
		fac05.raw \
		fac06.raw \
		cut01.raw \
		cut02.raw \
		cut03.raw \
		cut04.raw \
		cut05.raw \
		cut06.raw \
		cut07.raw \
		cut08.raw \
		cut09.raw \
		cut10.raw \
		cut11.raw \
		cut12.raw \
		cut13.raw  

all:	$(RAW)

clean:
	del *.raw

.wav.raw:
	vtor $*.wav $@


