//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by vdmplui.rc
//
#define IDD_TCP                         129
#define IDD_IPX                         130
#define IDD_NETBIOS                     131
#define IDD_MODEM                       132
#define IDC_SERVERADDR                  1000
#define IDC_REGSERVER                   1001
#define IDC_PORTNUMBER                  1003
#define IDC_LANA                        1004
#define IDC_STATIONNAME                 1005
#define IDC_SERVERNODE                  1006
#define IDC_SERVERNET                   1007
#define IDC_DIALNUMBER                  1009
#define IDC_CALLSETUP                   1010
#define IDC_LISTENSETUP                 1011
#define IDC_PORTNAME                    1012
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1013
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
