; CLW file contains information for the MFC ClassWizard

[General Info]
Version=1
LastClass=CVpdiagDlg
LastTemplate=CDialog
NewFileInclude1=#include "stdafx.h"
NewFileInclude2=#include "vpdiag.h"

ClassCount=3
Class1=CVpdiagApp
Class2=CVpdiagDlg
Class3=CAboutDlg

ResourceCount=3
Resource1=IDR_MAINFRAME
Resource2=IDD_VPDIAG_DIALOG (English (U.S.))
Resource3=IDD_ABOUTBOX (English (U.S.))

[CLS:CVpdiagApp]
Type=0
HeaderFile=vpdiag.h
ImplementationFile=vpdiag.cpp
Filter=N
LastObject=CVpdiagApp

[CLS:CVpdiagDlg]
Type=0
HeaderFile=vpdiagdl.h
ImplementationFile=vpdiagdl.cpp
Filter=D
LastObject=CVpdiagDlg
BaseClass=CDialog
VirtualFilter=dWC

[CLS:CAboutDlg]
Type=0
HeaderFile=vpdiagdl.h
ImplementationFile=vpdiagdl.cpp
Filter=D


[DLG:IDD_VPDIAG_DIALOG (English (U.S.))]
Type=1
ControlCount=11
Control1=IDC_TEST_TCP,button,1342242816
Control2=IDC_TCPHOSTNAME,edit,1350633600
Control3=IDC_IPXADDRESS,edit,1350633600
Control4=IDC_TCPADDRESS2,edit,1350633600
Control5=IDC_LANALIST,listbox,1352745219
Control6=IDC_STATIC,static,1342308354
Control7=IDC_STATIC,static,1342308354
Control8=IDC_STATIC,static,1342308354
Control9=IDC_STATIC,static,1342308354
Control10=IDC_TEST_IPX,button,1342242816
Control11=IDC_TEST_NETBIOS,button,1342242816
Class=CVpdiagDlg

[DLG:IDD_ABOUTBOX (English (U.S.))]
Type=1
ControlCount=4
Control1=IDC_STATIC,static,1342177283
Control2=IDC_STATIC,static,1342308480
Control3=IDC_STATIC,static,1342308352
Control4=IDOK,button,1342373889

