//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by WHATAMI.RC
//
#define IDS_STRING1                     1
#define IDS_STRING2                     2
#define IDS_STRING3                     3
#define IDS_STRING4                     4
#define IDS_STRING5                     5
#define IDS_STRING6                     6
#define IDS_STRING7                     7
#define IDD_MAIN                        105
#define IDC_OS                          1000
#define IDC_VC                          1001
#define IDC_DX                          1002
#define IDC_32S                         1003
#define IDC_WING                        1004
#define IDC_DOWNLOAD                    1005

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
